# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [15]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os


from config import g_key

ImportError: cannot import name 'g_key' from 'config' (C:\Users\jakob\Desktop\Git\python-api-challenge\WeatherPy\config.py)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path = "Output/city_weather_data.csv"
city_weather_df  = pd.read_csv(csv_path, encoding="utf-8")
city_weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,sao filipe,14.90,-24.50,74.05,80,11,4.99,CV,1591126355
1,buala,-8.14,159.59,81.61,78,39,7.34,SB,1591126355
2,mpika,-11.83,31.45,56.93,69,0,5.06,ZM,1591126355
3,ponta delgada,37.73,-25.67,60.80,87,40,19.46,PT,1591126355
4,vaini,-21.20,-175.20,77.00,83,20,6.93,TO,1591126355
...,...,...,...,...,...,...,...,...,...
558,kodinsk,58.69,99.18,43.66,80,6,2.82,RU,1591126433
559,hervey bay,-25.30,152.85,48.99,58,0,4.00,AU,1591126433
560,yar-sale,66.83,70.83,34.61,91,77,12.64,RU,1591126433
561,port-cartier,50.03,-66.87,60.80,42,75,14.99,CA,1591126433
562,grand gaube,-20.01,57.66,72.00,83,28,5.01,MU,1591126434

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure